amqStreams:
  kafka:
    name: amq
    version:
    replicas: 3
    image:
    listeners:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      # inter.broker.protocol.version: "3.3"
    storage:
      type: ephemeral
    authorization:
    rack:
    brokerRackInitImage:
    livenessProbe:
    readinessProbe:
    jvmOptions: 
    jmxOptions: 
    resources: 
    metricsConfig: 
    logging:
    template:
  zookeeper:
    replicas: 3
    image: 
    storage:
      type: ephemeral
    config: 
    livenessProbe:
    readinessProbe:
    jvmOptions: 
    jmxOptions: 
    resources: 
    metricsConfig:
    logging: 
    template: 
  entityOperator:
  clusterCa:
  clientsCa:
  cruiseControl:
  kafkaExporter:
  maintenanceTimeWindows:
  bridge:
  connects:
  mm2:
  topics:
  users: