amqStreams:
  namespace:
    name: helm-amq
    nodeSelector: 'env=amq-streams'
    displayName: 'AMQ Streams'
    description: 'AMQ Streams namespace automated with Helm'
  kafka:
    name: persistent-single-cluster
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false        
  zookeeper:
    replicas: 1
    storage:
      type: other
      size: 10Gi
  topics:
    - name: marvel
      partitions: 10
      replicas: 3
    - name: dc
      partitions: 6
      replicas: 2
    - name: dbz
      partitions: 15
      replicas: 3
#  users: