amqStreams:
  kafka:
    name: amq
  users:
    - name: admin
      authentication:
        type: tls
      authorization:
        type: simple
        acls:
          # Example ACL rules for marvel topic using consumer group my-group
          - resource:
              type: topic
              name: marvel
              patternType: literal
            operations:
              - Read
              - Describe
              - Write
              - Create
          - resource:
              type: group
              name: springboot
              patternType: literal
            operations: 
              - Read
              - Describe
      quotas:
        # consumerByteRate: 1
        # controllerMutationRate: 1
        # producerByteRate: 1
        # requestPercentage: 2