{{- if .Values.amqStreams.topics }}
{{- range $topic := .Values.amqStreams.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  labels:
    strimzi.io/cluster: {{ $.Values.amqStreams.kafka.name }}
spec:
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
{{- if $topic.config }}
  config:
    {{- toYaml $topic.config | nindent 4 }}
{{- else }}
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
{{- end }}
{{- end }}
{{- end }}