amqStreams:
  kafka:
    metricsConfig: true
    name: amq
    version: 3.3.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      # - name: tls
      #   port: 9093
      #   type: internal
      #   tls: true
    authorization:
      # 
    resources: 
      # requests:
      #   memory: 2Gi
      #   cpu:  1
      # limits:
      #   memory: 4Gi
      #   cpu: 2
    jvmOptions: 
      # -Xms: 2048
      # -Xmx: 2048        
    readinessProbe:
      # initialDelaySeconds: 15
      # timeoutSeconds: 5
    livenessProbe:
      # initialDelaySeconds: 15
      # timeoutSeconds: 5
    logging:      
      # 
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
    storage:
      type: ephemeral
      # type: jbod
      # volumes:
      # - id: 0
      #   type: persistent-claim
      #   size: 10Gi
      #   deleteClaim: false
    # metricsConfig:
      # type: jmxPrometheusExporter
      # valueFrom:
      #   configMapKeyRef:
      #     name: kafka-metrics
      #     key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    resources: 
      # requests:
      #   memory: 1Gi
      #   cpu:  500m
      # limits:
      #   memory: 2Gi
      #   cpu: 1
    jvmOptions: 
      # -Xms: 1024
      # -Xmx: 1024            
    readinessProbe:
      # initialDelaySeconds: 15
      # timeoutSeconds: 5
    livenessProbe:
      # initialDelaySeconds: 15
      # timeoutSeconds: 5
    storage:
      type: ephemeral
      # type: persistent-claim
      # size: 8Gi
      # deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  topics:
    # - name: marvel
    #   partitions: 10
    #   replicas: 1
  users:
    # - name: admin
          
